language: php

git:
    depth: 1

cache:
    directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

php:
- 7.1
- 7.2
- 7.3
- 7.4
- nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
- composer install

script:
- composer grumphp

after_success:
- phpenv config-rm xdebug.ini
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml